### ISSUE TITLE
panic when `fonts` dir is not present

### ISSUE THREAD

**Issue by flxzt** [tfachmann/typst-as-library#4]
The crate currently panics [here](https://github.com/tfachmann/typst-as-library/blob/dd9a93379b486dc0a2916b956360db84b496822e/src/lib.rs#L218) when no `fonts` dir is found.

I think it should search the system font paths as well, and maybe if nothing is found error out with a more descriptive message?

**Comment by tfachmann** [comment]
Yes, font handling should definitely be improved as it has been stated in #2 as well.

**Comment by flxzt** [comment]
oh sorry, I missed that.
