### ISSUE TITLE
Compilation issue for examples

### ISSUE THREAD

**Issue by mindreframer** [tfachmann/typst-as-library#9]
Thanks for this example! This looks quite interesting. When I try to compile the example, I get following error: 

folder: `/examples/native`.  
cmd: `cargo build --frozen`. 

```bash
error[E0277]: the trait bound `TypstWrapperWorld: World` is not satisfied
  --> src/main.rs:27:35
   |
27 |     let document = typst::compile(&world, &mut tracer).expect("Error compiling typst.");
   |                                   ^^^^^^ the trait `World` is not implemented for `TypstWrapperWorld`
   |
   = help: the following other types implement trait `World`:
             typst::_::__ComemoSurface<'__comemo_dynamic, '__comemo_tracked>
             typst::_::__ComemoSurfaceMut<'__comemo_dynamic, '__comemo_tracked>
   = note: required for the cast from `&TypstWrapperWorld` to `&dyn World`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `typst-as-library-example` (bin "typst-as-library-example") due to 1 previous error
```

Any possible hints? 

Thanks, Roman

**Comment by tfachmann** [comment]
Thanks a lot for your contribution, in the latest update to typst version `0.12.0`, we forgot to update the code of the example. The changes are done in https://github.com/tfachmann/typst-as-library/commit/ae0d50533b4df9eda8bd844e485fb16b4065c58b and the example should compile again.

**Comment by mindreframer** [comment]
@tfachmann Amazing! Thanks for the quick fix, this works now! Wo-hoo!
